name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go build -o go-home .

      - run: |
          sudo systemctl stop go-home || true
          sudo cp go-home /usr/local/bin/go-home
          sudo systemctl start go-home
